name: Release
on:
  push:
    tags: ["*"]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: mneil/cfnsane # list of Docker images to use as base name for tags
          tag-semver: |
            {{version}}
            {{major}}
            {{major}}.{{minor}}
      # - name: Push to Docker Hub
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: mneil/cfnsane
      #     tag_with_ref: true
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: docker.pkg.github.com
      #     repository:  mneil/cfnsane/cfnsane
      #     tag_with_ref: true

